name: ecodesk_flutter
description: Native Flutter implementation of the ecodesk.io chat widget.
version: 3.1.1
homepage: https://github.com/ecodesk-io/ecodesk_flutter

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: ^0.7.6
  http: ^1.3.0
  universal_io: ^2.2.2
  flutter_markdown: ^0.7.6+1
  timeago: ^3.7.0
  intl: ^0.19.0
  file_picker: ^8.3.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  open_filex: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  build_runner:
  flutter_lints:

flutter:
