name: ecodesk_flutter
description: Native Flutter implementation of the ecodesk.io chat widget.
version: 3.1.1
homepage: https://github.com/ecodesk-io/ecodesk_flutter

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket:
  http:
  universal_io:
  flutter_markdown:
  timeago:
  intl:
  file_picker:
  path_provider:
  url_launcher:
  open_filex:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  build_runner:
  flutter_lints:

flutter:
